module.exports = {
	build:{
		dest:"./resource/dest",
		// src 的作用： 根据文件到 src 的相对路径生成 发布到 dest 目录时的路径
		src:"./resource/src",
		base:"./resource/src/script",
		www:"./",
		pkg:[
			{
				main:/page\/a\.js$/,
				dest_rule:"$1.js",
				sub:[
					{
						dest_rule:"$pkg.js",
						contain:[
							/module_a\.js/,
							/module_b\.js/
						]
					}
				],
				except:[
					/\bjquery/,
					/\bunderscore/
				]
			}
		],
		paths:{
			tpl:'../tpl'
		},
		alias:{},
		available:[],
		ignore:[
			/^vacation\.json/,
			/^map\.json/,
			/\bdest\//,
			/\.md$/,
			/(^|\/)\./
		],
		availableType:["js","css","html"],
		uglify:{
			banner:"/*! lastmodify: $$today('yyyy-mm-dd HH:MM:ss') */\n",
			mangle:{
				except:["require","exports","module"]
			}
		}
	},
	server:{
		port:8181,
		defaultFile:"index.html",
		root:"./",
		rootRelative:"cwd",
		allowOrigin:""
	},
	contentType:{
		json:"application/json"
	}
};
